### ISSUE TITLE
NET Standard Support

### ISSUE THREAD

**Issue by oruchreis** [buunguyen/fasterflect#1] opened 2016-12-01 09:19 UTC
Could you consider to support net standard for net core projects?

**Comment by HelloKitty** [comment] 2017-02-16 20:03
@oruchreis I forked it last night and ported to to netstandard. I removed a couple XML things and I think Flags.ExactBinding wasn't compatible but that is about it.

I've yet to finish porting the unit tests to NUnit/XUnit to run tests against every framework so I'm not pushing it to official nuget until then. I currently use it on a private nuget feed and I'll report back if I finish any problems.

The repo is here: https://github.com/HelloKitty/fasterflect

**Comment by HelloKitty** [comment] 2017-02-16 21:29
@oruchreis out of 263 tests 56 are failing. They are related to type introspection for ctor and methods. I don't really have a solution.

edit: Down to 16. Though had to go through the standard reflection API so it won't be as fast for things such as ctor and eventually some method grabbing.

edit: Down to 4 failing tests. The library will still be slower because for some reason binding flags don't seem to be fully 1:1 for netstandard. Or I broke something. Can't tell which.

**Comment by HelloKitty** [comment] 2017-02-17 00:06
Maybe @buunguyen can come out of retirement and take a look.

**Comment by HelloKitty** [comment] 2017-02-17 00:30
Ok, all but one test passes now. I had to manually implement polymorphic parameter handling. Don't know why it didn't work out of the box. You won't always get the most accurate exceptions now if there is something wrong too. It also falls back to standard reflection if it encounters problems in some usecases. However, it will atleast work for now until someone does a better port or we get better parity in netstandard for reflection.

**Comment by buunguyen** [comment] 2017-08-25 18:48
@HelloKitty any update on this?

**Comment by HelloKitty** [comment] 2017-08-25 22:41
@buunguyen Hmmmm, a tiny bit. I forked and brought some of Fasterflect to Netstandard but I'm unfamiliar with some of the .NET Framework API you used for certain sections and/or couldn't find netstandard compatible equivalents. Now with Netstandard 2.0 it may be a lot easier. It'll compile, work and passes almost all of the unit tests you had. However caching in some sections is disabled. Which is kind of a big deal.

It's been awhile so I don't remember what part of caching had to be disabled. Hopefully my commits provide some information on what changed and why.

https://github.com/HelloKitty/fasterflect

**Comment by HelloKitty** [comment] 2017-08-25 22:47
Oh also, it uses an old version of the .netstandard project format. Still uses the json format. The majority of the issues were that reflection goes through TypeInfo now and a few parts of the API weren't available in netstandard1.6. I think netstandard2.0 resolves a lot of this but haven't checked.

**Comment by ffhighwind** [comment] 2019-12-08 17:19
I've added multiple platform support in my fork. The problem is that my fork is organized completely differently than the original.
https://github.com/ffhighwind/Fasterflect/blob/master/Fasterflect/Fasterflect.csproj

**Comment by danbopes** [comment] 2019-12-11 16:32
I would love to see this get updated for .net core

**Comment by ffhighwind** [comment] 2019-12-13 00:26
> I would love to see this get updated for .net core

Have you tried the .net standard version on nuget? I believe that's supposed to work with core. If it doesn't you could always make a few couple small changes to the csproj file like I did above and then compile it yourself.

**Comment by danbopes** [comment] 2019-12-13 01:56
Yup, that's what I ended up using, but would like to see the main package updated.

**Comment by buunguyen** [comment] 2019-12-13 02:05
I would appreciate a pull request to make this compatible with core/standard.

**Comment by benskid** [comment] 2020-05-12 16:29
> I would appreciate a pull request to make this compatible with core/standard.

Submitted a pull request with support for .Net Standard 2.0 just now. UT is all passing, did have to remove two methods that did not appear to be in use anyway. Please review.

I did not update the nuspec file or script to create the package. That would remain to be done (or alternatively, build the package from VS2019 directly?). Would also want to update the version number.

**Comment by buunguyen** [comment] 2020-05-19 18:36
Thanks @benskid for the PR and agreeing to be a collaborator. The update package (v3.0.0) is available on NuGet. Closing this issue now.

**Closed as completed by buunguyen** 2020-05-19 18:36 UTC
